services:
  postgres:
    image: postgres
    container_name: studex_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
# Production
#  studex:
#    image: studex
#    build:
#      context: .
#      dockerfile: Dockerfile
      
volumes:
  pgdata: